sudo: required
services:
  - docker

before_install:
  - docker build -t blghgbr/docker-react -f Dockerfile.dev .

script:
- docker run -e CI=true blghgbr/docker-react npm run test -- --coverage

language: generic 